#!/bin/sh

### hw ###
#   A Homework Preparation Script. 
#   Adds headers to main project files, creates a tarfile,
#   and emails the assignment to both myself and the grader.
#   Also forces my hand in creating documentation.
#   Requires the following applications:
#  
#   mutt
#   vim
#   sed
#   cat
#   echo
#   tar
#   gzip
#
#   Before executing, be sure you 
#       1.) have a preexisting ~/tmp directory
#       2.) this script is in your path
#       3.) You are in the directory of your submission
#
###


### File Variables ###
# Name of the tar directory to be emailed.
TARDIR=""
TARFILE="$TARDIR.tar"
APPNAME=""
HEADERFILE="~/tmp/header.txt"

### Output Variables ###
COURSENAME=""
ASSIGNMENT=""
ADDRESS1=""
ADDRESS2=""
SUBJECT=""
ARCMD="tar czvf $TARDIR.tar $TARDIR"

# Small temp file created during usage.
TMPFILE="~/tmp/header.txt.tmp"


### Script Start ###
echo "Cleaning up..."
rm -rf $TARDIR
echo "Creating directory..."
mkdir $TARDIR
echo "Copying targets..."
cp Makefile *.txt $TARDIR/

### Add headers to the main files ###
### Opens vim on each file.
echo "Creating headers..."

cp $HEADERFILE $TMPFILE
sed -i "/__assignment__/ s/__assignment__/$ASSIGNMENT/g" $TMPFILE
sed -i "/__coursename__/ s/__coursename__/$COURSENAME/g" $TMPFILE 

for filename in *.h
do 
	cat $TMPFILE >> ./$TARDIR/${filename}
	sed -i "/__filename__/ s/__filename__/${filename}/g" ./$TARDIR/${filename} 
	vim "+/__purpose__" ./$TARDIR/${filename} 
	cat ${filename} >> ./$TARDIR/${filename}
done

for filename in *.cpp
do 
	cat $TMPFILE >> ./$TARDIR/${filename}
	sed -i "/__filename__/ s/__filename__/${filename}/g" ./$TARDIR/${filename}
	vim "+/__purpose__" ./$TARDIR/${filename} 
	cat ${filename} >> ./$TARDIR/${filename}
done

### Get rid of temp files ###
rm -rf $TMPFILE $TARDIR $TARFILE

### Create an archive ###
echo "Creating archive..."
$ARCMD 

### Send out the email ###
echo "Sending email..."
echo "Please compile on Linux Lab systems. Type 'tar xvf $TARDIR.tar.gz' to expand archive." | mutt -x -a $TARFILE -s $SUBJECT $ADDRESS1 
echo "Please compile on Linux Lab systems. Type 'tar xvf $TARDIR.tar.gz' to expand archive." | mutt -x -a $TARFILE -s $SUBJECT $ADDRESS2 

echo "Done."

